## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_IGW {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-08-04T17:21:18.586Z"
  }
  display_name = "IGW"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_VCN01-SP.id
}

resource oci_core_instance_configuration export_SRV-WEB {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-04T15:35:27.588Z"
  }
  display_name = "SRV-WEB"
  freeform_tags = {
  }
  instance_details {
    instance_type = "compute"
    launch_details {
      agent_config {
        #are_all_plugins_disabled = <<Optional value not found in discovery>>
        is_management_disabled = "false"
        is_monitoring_disabled = "false"
        plugins_config {
          desired_state = "DISABLED"
          name          = "Vulnerability Scanning"
        }
        plugins_config {
          desired_state = "DISABLED"
          name          = "Management Agent"
        }
        plugins_config {
          desired_state = "ENABLED"
          name          = "Custom Logs Monitoring"
        }
        plugins_config {
          desired_state = "ENABLED"
          name          = "Compute Instance Monitoring"
        }
        plugins_config {
          desired_state = "DISABLED"
          name          = "Bastion"
        }
      }
      availability_config {
        recovery_action = "RESTORE_INSTANCE"
      }
      availability_domain = data.oci_identity_availability_domain.export_ArmX-SA-SAOPAULO-1-AD-1.name
      #capacity_reservation_id = <<Optional value not found in discovery>>
      compartment_id = oci_license_manager_configuration.export_configuration.id
      create_vnic_details {
        assign_private_dns_record = "true"
        assign_public_ip          = "true"
        #defined_tags = <<Optional value not found in discovery>>
        #display_name = <<Optional value not found in discovery>>
        freeform_tags = {
        }
        #hostname_label = <<Optional value not found in discovery>>
        nsg_ids = [
        ]
        #private_ip = <<Optional value not found in discovery>>
        #skip_source_dest_check = <<Optional value not found in discovery>>
        subnet_id = oci_core_subnet.export_SubNet_Public.id
      }
      #dedicated_vm_host_id = <<Optional value not found in discovery>>
      #defined_tags = <<Optional value not found in discovery>>
      #display_name = <<Optional value not found in discovery>>
      extended_metadata = {
      }
      #fault_domain = <<Optional value not found in discovery>>
      freeform_tags = {
      }
      instance_options {
        are_legacy_imds_endpoints_disabled = "false"
      }
      #ipxe_script = <<Optional value not found in discovery>>
      is_pv_encryption_in_transit_enabled = "true"
      launch_mode                         = ""
      #launch_options = <<Optional value not found in discovery>>
      metadata = {
        "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu8BRKQCbp1AY8gOlGMbRPhYkKb96zLssZW9SdhnBZJmhhBzsYxURA3A45kpNFW9sWltKL8WbhV02o1o/BS4/DctCZOyxtmoDv47v8xwDhNR9Nq8jVag2bsdzxtBBySK6IPSESSmrMRg4zXyC3hCSgXPzdYX9gbIE7IRqY0jQy66fRut3p1ELOguGmyuK6pTw8u41y+1C8pjJvBe/qowVCep6qz8OVZJ+RRWsBRPr5gCOaOQN68r/vDL5v4oSug4/2esb6mqJxfmRp7W5Mr+2pGGTWMah2HKrsa53tK6rDVaZaREj46LVyYIUeE0rAO99fwtEB+DWxfNto+nZqHuiF ssh-key-2022-09-04"
      }
      #platform_config = <<Optional value not found in discovery>>
      #preemptible_instance_config = <<Optional value not found in discovery>>
      preferred_maintenance_action = ""
      shape                        = "VM.Standard.E2.1.Micro"
      #shape_config = <<Optional value not found in discovery>>
      source_details {
        #boot_volume_id = <<Optional value not found in discovery>>
        #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
        #boot_volume_vpus_per_gb = <<Optional value not found in discovery>>
        image_id    = "ocid1.image.oc1.sa-saopaulo-1.aaaaaaaawyqwfxyjb2ujxv7qwabgp77sstxkf6fzxlgu4kjegkhigqpyoeca"
        source_type = "image"
      }
    }
  }
  #instance_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
}

resource oci_core_drg_attachment export_drgattachment20220903150559 {
  defined_tags = {
  }
  display_name       = "drgattachment20220903150559"
  drg_id             = oci_core_drg.export_GWRD.id
  drg_route_table_id = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-VCN-attachments.id
  #export_drg_route_distribution_id = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  network_details {
    id = oci_core_vcn.export_VCN01-SP.id
    #route_table_id = <<Optional value not found in discovery>>
    type           = "VCN"
    vcn_route_type = "SUBNET_CIDRS"
  }
  #remove_export_drg_route_distribution_trigger = <<Optional value not found in discovery>>
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_VCN01-SP.id
}

resource oci_core_vcn export_VCN01-SP {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/20",
  ]
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "VCN01SP"
    "Oracle-Tags.CreatedOn" = "2022-08-04T17:11:50.588Z"
  }
  display_name = "VCN01-SP"
  dns_label    = "vcn01sp"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_subnet export_SubNet_Public {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.15.0/24"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-08-04T21:44:50.717Z"
  }
  dhcp_options_id = oci_core_vcn.export_VCN01-SP.default_dhcp_options_id
  display_name    = "SubNet_Public"
  dns_label       = "subnetpublic"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_VCN01-SP.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_VCN01-SP.default_security_list_id,
    oci_core_security_list.export_SL_public.id,
  ]
  vcn_id = oci_core_vcn.export_VCN01-SP.id
}

resource oci_core_drg export_GWRD {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-03T15:05:31.820Z"
  }
  display_name = "GWRD"
  freeform_tags = {
  }
}

resource oci_core_private_ip export_SRV-belloinfo {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-16T10:02:04.184Z"
  }
  display_name = "SRV-belloinfo"
  freeform_tags = {
  }
  hostname_label = "srv-belloinfo"
  ip_address     = "10.0.15.55"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.sa-saopaulo-1.abtxeljra75l75a3u7cr2b7fnawy5yanrfxvfsyyc7jw4lyv25tvwq64bbya"
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-VCN01-SP {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "VCN01SP"
    "Oracle-Tags.CreatedOn" = "2022-08-04T17:11:50.588Z"
  }
  display_name     = "Default DHCP Options for VCN01-SP"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_VCN01-SP.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcn01sp.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_GW_NAT {
  block_traffic  = "false"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-08-04T21:51:04.543Z"
  }
  display_name = "GW_NAT"
  freeform_tags = {
  }
  public_ip_id = "ocid1.publicip.oc1.sa-saopaulo-1.aaaaaaaaxdkejlxbjiza5xmqtwso3cd6ovsrjf2ok2baf75kig5ink7cc5na"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_VCN01-SP.id
}

resource oci_core_route_table export_RT_SubNet_Private {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-08-04T21:59:05.529Z"
  }
  display_name = "RT_SubNet_Private"
  freeform_tags = {
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_GW_NAT.id
    #route_type = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_VCN01-SP.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-VCN01-SP {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "VCN01SP"
    "Oracle-Tags.CreatedOn" = "2022-08-04T17:11:50.588Z"
  }
  display_name = "Default Route Table for VCN01-SP"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_VCN01-SP.default_route_table_id
  route_rules {
    description       = "Internet Gateway criado manual"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_IGW.id
    #route_type = <<Optional value not found in discovery>>
  }
}

resource oci_core_security_list export_SL_private {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-08-28T14:44:57.559Z"
  }
  display_name = "SL_private"
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "3306"
      min = "3306"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_VCN01-SP.id
}

resource oci_core_security_list export_SL_public {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-08-28T07:23:16.034Z"
  }
  display_name = "SL_public"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "HTTP"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "HTTPS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "17"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    udp_options {
      max = "1194"
      min = "1194"
      #source_port_range = <<Optional value not found in discovery>>
    }
  }
  vcn_id = oci_core_vcn.export_VCN01-SP.id
}

resource oci_core_default_security_list export_Default-Security-List-for-VCN01-SP {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "VCN01SP"
    "Oracle-Tags.CreatedOn" = "2022-08-04T17:11:50.588Z"
  }
  display_name = "Default Security List for VCN01-SP"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/20"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_VCN01-SP.default_security_list_id
}

resource oci_core_instance export_SRV-belloinfo_1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain--ArmX-SA-SAOPAULO-1-AD-1
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = oci_license_manager_configuration.export_configuration.id
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
      "Oracle-Tags.CreatedOn" = "2022-09-16T10:02:04.184Z"
    }
    display_name = "SRV-belloinfo"
    freeform_tags = {
    }
    hostname_label = "srv-belloinfo"
    nsg_ids = [
    ]
    private_ip             = "10.0.15.55"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_SubNet_Public.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-16T10:02:03.986Z"
  }
  display_name = "SRV-belloinfo"
  extended_metadata = {
  }
  fault_domain = var.fault_domain--FAULT-DOMAIN-3
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "true"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCybNsePeHG3uNK2+SVexZ6qoLk8Fa2BJLpHfqVVyYQ8iF8iv8UzWcCoY527IFCwDp/nxbFdEaFkiQ2IYHahiEqBIbq2nVdkcejIlAYhGAbPjdpnqIgXf2kjD4sxtxghf2Y2CQUJdYKMy8D7hlWIHk9AjeDZBxDTdKG9o/6xzymHQn2uo1Bme3DA1tj7qJwhvS5dqzRCo5sTngFcqeIkLylk3hh+wWAKAWMvSGo52Qc+St/K2JgvT+K3B9G7CKip2T4bfBsxKssQv9Qlonddjj9q1CsKIg0C02gHStlS+hUg4w+TS0UCy7/46+lGRZRwJm2OM2XJT+3tvwXXDNCyhdR ssh-key-2022-09-16"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.A1.Flex"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "6"
    nvmes                     = "0"
    ocpus                     = "1"
  }
  source_details {
    boot_volume_size_in_gbs = "50"
    boot_volume_vpus_per_gb = "10"
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_SRV-belloinfo_1
    source_type = "image"
  }
  state = "RUNNING"
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-ALL-routes {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for ALL routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_GWRD.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_distribution export_Autogenerated-Import-Route-Distribution-for-VCN-Routes {
  defined_tags = {
  }
  display_name      = "Autogenerated Import Route Distribution for VCN Routes"
  distribution_type = "IMPORT"
  drg_id            = oci_core_drg.export_GWRD.id
  freeform_tags = {
  }
}

resource oci_core_drg_route_table export_Autogenerated-Drg-Route-Table-for-VCN-attachments {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-03T15:05:31.820Z"
  }
  display_name = "Autogenerated Drg Route Table for VCN attachments"
  drg_id       = oci_core_drg.export_GWRD.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-ALL-routes.id
  is_ecmp_enabled                  = "false"
  #remove_import_trigger = <<Optional value not found in discovery>>
}

resource oci_core_drg_route_table export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-03T15:05:31.820Z"
  }
  display_name = "Autogenerated Drg Route Table for RPC, VC, and IPSec attachments"
  drg_id       = oci_core_drg.export_GWRD.id
  freeform_tags = {
  }
  import_drg_route_distribution_id = oci_core_drg_route_distribution.export_Autogenerated-Import-Route-Distribution-for-VCN-Routes.id
  is_ecmp_enabled                  = "false"
  #remove_import_trigger = <<Optional value not found in discovery>>
}

resource oci_core_drg_route_table_route_rule export_Autogenerated-Drg-Route-Table-for-VCN-attachments_drg_route_table_route_rule_1 {
  destination                = "10.0.15.0/24"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-VCN-attachments.id
  next_hop_drg_attachment_id = oci_core_drg_attachment.export_drgattachment20220903150559.id
}

resource oci_core_drg_route_table_route_rule export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments_drg_route_table_route_rule_1 {
  destination                = "10.0.15.0/24"
  destination_type           = "CIDR_BLOCK"
  drg_route_table_id         = oci_core_drg_route_table.export_Autogenerated-Drg-Route-Table-for-RPC-VC-and-IPSec-attachments.id
  next_hop_drg_attachment_id = oci_core_drg_attachment.export_drgattachment20220903150559.id
}

