## This configuration was generated by terraform-provider-oci

resource oci_identity_compartment export_ManagedCompartmentForPaaS {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "idcs-f41403aac8c84944bd498a7f724a2a77|25145809|Belicio Cardoso"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "ManagedCompartmentForPaaS"
}

resource oci_identity_domain export_Default {
  #admin_email = <<Optional value not found in discovery>>
  #admin_first_name = <<Optional value not found in discovery>>
  #admin_last_name = <<Optional value not found in discovery>>
  #admin_user_name = <<Optional value not found in discovery>>
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description  = "Default domain"
  display_name = "Default"
  freeform_tags = {
  }
  home_region        = "sa-saopaulo-1"
  is_hidden_on_login = "false"
  #is_notification_bypassed = <<Optional value not found in discovery>>
  #is_primary_email_required = <<Optional value not found in discovery>>
  license_type = "free"
  state        = "ACTIVE"
}

resource oci_identity_policy export_PSM-mgd-comp-policy {
  compartment_id = oci_identity_compartment.export_ManagedCompartmentForPaaS.id
  defined_tags = {
  }
  description = "PSM managed compartment policy"
  freeform_tags = {
  }
  name = "PSM-mgd-comp-policy"
  statements = [
    "allow any-user to read all-resources in compartment managedcompartmentforpaas",
    "allow service PSM to manage all-resources in compartment managedcompartmentforpaas",
    "allow any-user to manage virtual-network-family in compartment managedcompartmentforpaas where all { target.vcn.display-name != /mgmt-vcn*/, request.operation != 'CreateVcn' }",
    "allow any-user to use buckets in compartment managedcompartmentforpaas where request.instance.compartment.id = 'ocid1.compartment.oc1..aaaaaaaab5ab26ulyep4c5tfngee3nxl2ouq6itviyaliujsqjvtntqklo2a'",
    "allow any-user to use objects in compartment managedcompartmentforpaas where request.instance.compartment.id = 'ocid1.compartment.oc1..aaaaaaaab5ab26ulyep4c5tfngee3nxl2ouq6itviyaliujsqjvtntqklo2a'",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_BootstrapProvisioning {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "Temporary policy for /bootstrapDefaultDomain API's whitelisted services. Gives access to IAM work request APIs and ability to delete these policy when access is no longer needed."
  freeform_tags = {
  }
  name = "BootstrapProvisioning"
  statements = [
    "ALLOW SERVICE tenancylifecycleservice to {IAM_WORKREQUEST_READ, IAM_WORKREQUEST_INSPECT} IN TENANCY",
    "ALLOW SERVICE tenancylifecycleservice to {POLICY_DELETE} IN TENANCY where target.policy.name='BootstrapProvisioning'",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_PSM-root-policy-compartments {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "PSM managed compartment root policy"
  freeform_tags = {
  }
  name = "PSM-root-policy-compartments"
  statements = [
    "allow service PSM to manage all-resources in compartment managedcompartmentforpaas",
    "allow service OracleEnterpriseManager to manage all-resources in compartment managedcompartmentforpaas",
    "allow service PSM to manage users in tenancy where target.user.name = /__PSM*/",
    "allow any-user to manage all-resources in compartment managedcompartmentforpaas where request.user.name = /__PSM*/",
    "allow any-user to manage all-resources in compartment managedcompartmentforpaas where request.instance.compartment.id = 'ocid1.compartment.oc1..aaaaaaaab5ab26ulyep4c5tfngee3nxl2ouq6itviyaliujsqjvtntqklo2a'",
    "allow service PSM to inspect tenant in tenancy",
    "allow service PSM to inspect compartments in tenancy",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_policy export_Tenant-Admin-Policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "Tenant Admin Policy"
  freeform_tags = {
  }
  name = "Tenant Admin Policy"
  statements = [
    "ALLOW GROUP Administrators to manage all-resources IN TENANCY",
  ]
  #version_date = <<Optional value not found in discovery>>
}

resource oci_identity_group export_All-Domain-Users {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "A group representing all users."
  freeform_tags = {
  }
  name = "All Domain Users"
}

resource oci_identity_group export_Administrators {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "Administrators"
  freeform_tags = {
  }
  name = "Administrators"
}

resource oci_identity_authentication_policy export_authentication_policy {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  network_policy {
    network_source_ids = [
    ]
  }
  password_policy {
    is_lowercase_characters_required = "true"
    is_numeric_characters_required   = "true"
    is_special_characters_required   = "false"
    is_uppercase_characters_required = "true"
    is_username_containment_allowed  = "false"
    minimum_password_length          = "12"
  }
}

resource oci_identity_user export_belloinfo-gmail-com {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "belloinfo@gmail.com"
  freeform_tags = {
  }
  name = "belloinfo@gmail.com"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_user export_josecardoso {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-08-31T17:00:28.417Z"
  }
  description = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  email       = "belloinfo@hotmail.com"
  freeform_tags = {
  }
  name = "josecardoso"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [description]
  }
}

resource oci_identity_api_key export_belloinfo-gmail-com_api_key_1 {
  key_value = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlOUOv8EZKrmuqIMZGjOf\nVtpoXnrV6hgZPzGfwZmNRlrT4REAHqpFeJobJWSMfD4nhkeawutoJ/IlGMmg4ixY\nP9mm1/Uo3OV8RRcRIOSc9FQW+JBEruPKexfp0Ytf4i1AkcH7K8kB8cjHgHdBqH/j\n/nkQI3zaPIK6ncCjGguQ2rPhUfMSw3HoGF5lqjb53PcCU03Xq9idqG7iVW+8iGeV\nCeWoL7ZJwhRlknWpZqW67cNnwrrmoICOy77ARqtICRr7QR1kzHtIBZRyCCt7mTNy\nqo9BSdKICXBCdUWnMWimwY7rAR3YRlkx6ywhCiToTXMa9FCvVru/hXrn8iUfpo6i\nrwIDAQAB\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_belloinfo-gmail-com.id
}

resource oci_identity_ui_password export_belloinfo-gmail-com_ui_password {
  user_id = oci_identity_user.export_belloinfo-gmail-com.id
}

resource oci_identity_user_group_membership export_belloinfo-gmail-com_user_group_membership_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_belloinfo-gmail-com.id
}

resource oci_identity_api_key export_josecardoso_api_key_1 {
  key_value = "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtOUFEXIJhyCZ6x0J/Vae\r\nTE0eTChiOo0Q1I3NU0zw/xAu5WoYMj3atPfkAjMRHAc1fMCmo4dN2C5ng4B6lOC7\r\nodsr5zvU75rnq9GqnmzPcYPWscxIyT2mobkpuSfhzAoEMwH6pgOAa/j21tkW6pdY\r\nX6XD5dk9luVRMMt6BT91SS5IehzjynFJBbopT+4hahsDuZOI6sS53gaEsMDaC+Zb\r\n2QQkkkR86upv8EErflQvETQ9zV1hbojNp/um5abU+jlF7DZ9DA7s22zxQyi5CuPu\r\nuPzrP+E0977pmJ3MDC3sNdjdSTMWCGbh7POtlHlmM8dl8ZKbllh1R5uM1HvdmHFS\r\njQIDAQAB\r\n-----END PUBLIC KEY-----"
  user_id   = oci_identity_user.export_josecardoso.id
}

resource oci_identity_ui_password export_josecardoso_ui_password {
  user_id = oci_identity_user.export_josecardoso.id
}

resource oci_identity_user_group_membership export_josecardoso_user_group_membership_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  group_id       = oci_identity_group.export_Administrators.id
  user_id        = oci_identity_user.export_josecardoso.id
}

