## This configuration was generated by terraform-provider-oci

resource oci_license_manager_configuration export_configuration {
  compartment_id = "ocid1.tenancy.oc1..aaaaaaaae4w7y3jpdhmojsky5azv5ywoiqbptvrajmpnfavu4rt2aupfgi4a"
  email_ids = [
  ]
}

