## This configuration was generated by terraform-provider-oci

resource oci_monitoring_alarm export_mem-90 {
  body           = "Alerta do alto uso da memória."
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-04T13:40:47.052Z"
  }
  destinations = [
    oci_ons_notification_topic.export_Alerta-mem-90.id,
  ]
  display_name = "mem-90"
  freeform_tags = {
  }
  is_enabled                                    = "true"
  is_notifications_per_metric_dimension_enabled = "false"
  message_format                                = "ONS_OPTIMIZED"
  metric_compartment_id                         = oci_license_manager_configuration.export_configuration.id
  metric_compartment_id_in_subtree              = "false"
  namespace                                     = "oci_computeagent"
  pending_duration                              = "PT1M"
  query                                         = "MemoryUtilization[60m]{resourceId = \"ocid1.instance.oc1.sa-saopaulo-1.antxeljrws2464qcyqks5p2rxochzhgdk5fczlf3ogqvziwwbkmlig5vx6na\"}.mean() > 90"
  repeat_notification_duration                  = "PT2M"
  resolution                                    = "1m"
  #resource_group = <<Optional value not found in discovery>>
  severity = "CRITICAL"
}

