## This configuration was generated by terraform-provider-oci

data oci_objectstorage_namespace export_namespace {
  compartment_id = oci_license_manager_configuration.export_configuration.id
}
resource oci_objectstorage_bucket export_bucket-revogacao {
  access_type    = "NoPublicAccess"
  auto_tiering   = "Disabled"
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-01T10:06:01.344Z"
  }
  freeform_tags = {
  }
  #kms_key_id = <<Optional value not found in discovery>>
  metadata = {
  }
  name                  = "bucket-revogacao"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  object_events_enabled = "false"
  storage_tier          = "Standard"
  versioning            = "Disabled"
}

