## This configuration was generated by terraform-provider-oci

resource oci_ons_subscription export_subscription_1 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-04T13:40:42.117Z"
  }
  delivery_policy = "{\"backoffRetryPolicy\":{\"maxRetryDuration\":7200000,\"policyType\":\"EXPONENTIAL\"}}"
  endpoint        = "belloinfo@gmail.com"
  freeform_tags = {
  }
  protocol = "EMAIL"
  topic_id = oci_ons_notification_topic.export_Alerta-mem-90.id
}

resource oci_ons_notification_topic export_Alerta-mem-90 {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/belloinfo@gmail.com"
    "Oracle-Tags.CreatedOn" = "2022-09-04T13:40:41.170Z"
  }
  #description = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "Alerta-mem-90"
}

