## This configuration was generated by terraform-provider-oci

resource oci_identity_tag_namespace export_Oracle-Tags {
  compartment_id = oci_license_manager_configuration.export_configuration.id
  defined_tags = {
  }
  description = "The namespace for the automatic tags."
  freeform_tags = {
  }
  is_retired = "false"
  name       = "Oracle-Tags"
}

resource oci_identity_tag_default export_tag_default_1 {
  compartment_id    = oci_license_manager_configuration.export_configuration.id
  is_required       = "false"
  tag_definition_id = "ocid1.tagdefinition.oc1..aaaaaaaahidpx2u3iwwe55xhayf5j24ikvjz3rqtv25sqnvk2calrwhhp25q"
  value             = "$${iam.principal.name}"
}

resource oci_identity_tag_default export_tag_default_2 {
  compartment_id    = oci_license_manager_configuration.export_configuration.id
  is_required       = "false"
  tag_definition_id = "ocid1.tagdefinition.oc1..aaaaaaaavehwtqie74uvwgdahefgomftp4zzlnroh2k7dkcs3q2eozxlx4uq"
  value             = "$${oci.datetime}"
}

resource oci_identity_tag export_CreatedBy {
  defined_tags = {
  }
  description = "The name of the principal that created the resource."
  freeform_tags = {
  }
  is_cost_tracking = "true"
  is_retired       = "false"
  name             = "CreatedBy"
  tag_namespace_id = oci_identity_tag_namespace.export_Oracle-Tags.id
}

resource oci_identity_tag export_CreatedOn {
  defined_tags = {
  }
  description = "The date and time that the resource was created."
  freeform_tags = {
  }
  is_cost_tracking = "false"
  is_retired       = "false"
  name             = "CreatedOn"
  tag_namespace_id = oci_identity_tag_namespace.export_Oracle-Tags.id
}

